### ISSUE TITLE
hdfs_connection.c:40:5: error: incompatible type for argument 5 of ‘DBOpenConnection’

### ISSUE THREAD

**Issue by neshwill** [EnterpriseDB/hdfs_fdw#12]
hi i have a problem with compile it . 

<code>

 hdfs_fdw]# make -j2  USE_PGXS=1
gcc -Wall -Wmissing-prototypes -Wpointer-arith -Wdeclaration-after-statement -Wendif-labels -Wmissing-format-attribute -Wformat-security -fno-strict-aliasing -fwrapv -fexcess-precision=standard -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -mtune=generic -DLINUX_OOM_ADJ=0 -fpic -Wno-unused-variable -I/data/123/thrift-0.9.3/hdfs_fdw/libhive  -I/data/123/thrift-0.9.3/hdfs_fdw/libhive/odbc  -I/data/123/thrift-0.9.3/hdfs_fdw/libhive/odbc2 -DHAVE_NETINET_IN_H -DHAVE_INTTYPES_H  -I. -I./ -I/usr/pgsql-9.5/include/server -I/usr/pgsql-9.5/include/internal -D_GNU_SOURCE -I/usr/include/libxml2  -I/usr/include  -c -o hdfs_client.o hdfs_client.c
gcc -Wall -Wmissing-prototypes -Wpointer-arith -Wdeclaration-after-statement -Wendif-labels -Wmissing-format-attribute -Wformat-security -fno-strict-aliasing -fwrapv -fexcess-precision=standard -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -mtune=generic -DLINUX_OOM_ADJ=0 -fpic -Wno-unused-variable -I/data/123/thrift-0.9.3/hdfs_fdw/libhive  -I/data/123/thrift-0.9.3/hdfs_fdw/libhive/odbc  -I/data/123/thrift-0.9.3/hdfs_fdw/libhive/odbc2 -DHAVE_NETINET_IN_H -DHAVE_INTTYPES_H  -I. -I./ -I/usr/pgsql-9.5/include/server -I/usr/pgsql-9.5/include/internal -D_GNU_SOURCE -I/usr/include/libxml2  -I/usr/include  -c -o hdfs_query.o hdfs_query.c
gcc -Wall -Wmissing-prototypes -Wpointer-arith -Wdeclaration-after-statement -Wendif-labels -Wmissing-format-attribute -Wformat-security -fno-strict-aliasing -fwrapv -fexcess-precision=standard -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -mtune=generic -DLINUX_OOM_ADJ=0 -fpic -Wno-unused-variable -I/data/123/thrift-0.9.3/hdfs_fdw/libhive  -I/data/123/thrift-0.9.3/hdfs_fdw/libhive/odbc  -I/data/123/thrift-0.9.3/hdfs_fdw/libhive/odbc2 -DHAVE_NETINET_IN_H -DHAVE_INTTYPES_H  -I. -I./ -I/usr/pgsql-9.5/include/server -I/usr/pgsql-9.5/include/internal -D_GNU_SOURCE -I/usr/include/libxml2  -I/usr/include  -c -o hdfs_option.o hdfs_option.c
gcc -Wall -Wmissing-prototypes -Wpointer-arith -Wdeclaration-after-statement -Wendif-labels -Wmissing-format-attribute -Wformat-security -fno-strict-aliasing -fwrapv -fexcess-precision=standard -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -mtune=generic -DLINUX_OOM_ADJ=0 -fpic -Wno-unused-variable -I/data/123/thrift-0.9.3/hdfs_fdw/libhive  -I/data/123/thrift-0.9.3/hdfs_fdw/libhive/odbc  -I/data/123/thrift-0.9.3/hdfs_fdw/libhive/odbc2 -DHAVE_NETINET_IN_H -DHAVE_INTTYPES_H  -I. -I./ -I/usr/pgsql-9.5/include/server -I/usr/pgsql-9.5/include/internal -D_GNU_SOURCE -I/usr/include/libxml2  -I/usr/include  -c -o hdfs_deparse.o hdfs_deparse.c
gcc -Wall -Wmissing-prototypes -Wpointer-arith -Wdeclaration-after-statement -Wendif-labels -Wmissing-format-attribute -Wformat-security -fno-strict-aliasing -fwrapv -fexcess-precision=standard -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -mtune=generic -DLINUX_OOM_ADJ=0 -fpic -Wno-unused-variable -I/data/123/thrift-0.9.3/hdfs_fdw/libhive  -I/data/123/thrift-0.9.3/hdfs_fdw/libhive/odbc  -I/data/123/thrift-0.9.3/hdfs_fdw/libhive/odbc2 -DHAVE_NETINET_IN_H -DHAVE_INTTYPES_H  -I. -I./ -I/usr/pgsql-9.5/include/server -I/usr/pgsql-9.5/include/internal -D_GNU_SOURCE -I/usr/include/libxml2  -I/usr/include  -c -o hdfs_connection.o hdfs_connection.c
hdfs_connection.c: In function ‘hdfs_get_connection’:
hdfs_connection.c:40:5: error: incompatible type for argument 5 of ‘DBOpenConnection’
     512);
     ^
In file included from hdfs_fdw.h:19:0,
                 from hdfs_connection.c:17:
libhive/odbc/hiveclient.h:109:17: note: expected ‘char _’ but argument is of type ‘CLIENT_TYPE’
 HiveConnection_ DBOpenConnection(const char\* database, const char\* host, int port, int framed,
                 ^
hdfs_connection.c:40:5: error: too many arguments to function ‘DBOpenConnection’
     512);
     ^
In file included from hdfs_fdw.h:19:0,
                 from hdfs_connection.c:17:
libhive/odbc/hiveclient.h:109:17: note: declared here
 HiveConnection\* DBOpenConnection(const char\* database, const char\* host, int port, int framed,
                 ^
make: **\* [hdfs_connection.o] Error 1
make: **\* Waiting for unfinished jobs....

</code>

**Comment by ibrarahmad** [comment]
We are not using thrift anymore, so please try now.
