### ISSUE TITLE
libfb303.so: undefined symbol

### ISSUE THREAD

**Issue by parisni** [EnterpriseDB/hdfs_fdw#16]
Hello,

CREATE EXTENSION hdfs_fdw;
ERROR couldn't load library « /usr/pgsql-9.5/lib/hdfs_fdw.so » : /usr/pgsql-9.5/lib/libfb303.so: undefined symbol: _ZNK6apache6thrift11concurrency14ReadWriteMutex11acquireReadEv

OS: Red Hat  6.7
PG: 9.5.1

Have you any thought ?

Thanks

**Comment by ibrarahmad** [comment]
No more issue now, not using this library anymore.
