### ISSUE TITLE
Update the readme file

### ISSUE THREAD

**Issue by gabbasb** [EnterpriseDB/hdfs_fdw#43]
Changes in read me file are required because
1. LD_LIBRARY_PATH is not required and is replaced by GUC hdfs_fdw.jvmpath
2. A new option auth_type is added in CREATE SERVER
3. A new value is added in client_type.

**Comment by jeevanladhe** [comment]
Addressed as part of commit `830d3b201b6848b5d5e960f5d3ec7885a0cfd995`.
