### ISSUE TITLE
Failed to connect to hive server

### ISSUE THREAD

**Issue by zhaoyuan2022** [EnterpriseDB/hdfs_fdw#69]
Hi, 

I am trying to use hdfs_fdw against postgres 12.
The hive server is running smoothly, I can access hdfs and postgres data with the beeline command,  and I have update the hive-site.conf to make it use the NOSASL auth type. 
![截屏2022-07-21 下午6 36 46](https://user-images.githubusercontent.com/107826742/180194601-343db06c-fefe-4bab-a4f9-e6d0f2941492.png)
![截屏2022-07-21 下午6 37 52](https://user-images.githubusercontent.com/107826742/180194629-2a3a7bab-ac33-47aa-b003-f40c0898e415.png)

The steps to reproduce the problem: 
1. create hdfs_fdw extension.
2. create hdfs_fdw server
'CREATE SERVER hdfs_server
FOREIGN DATA WRAPPER hdfs_fdw
OPTIONS (host 'localhost', auth_type 'NOSASL');'
3.  create user mapping
'CREATE USER MAPPING FOR test_user SERVER hdfs_server OPTIONS (username 'hive');'
![截屏2022-07-21 下午6 34 52](https://user-images.githubusercontent.com/107826742/180194040-ef74cdc4-e42c-4a17-8088-2d10edf311af.png)

_NOTE: another server and user mapping definition like:
'CREATE SERVER hdfs_server
FOREIGN DATA WRAPPER hdfs_fdw
OPTIONS (host 'localhost');
CREATE USER MAPPING FOR test_user SERVER hdfs_server;
'_
![截屏2022-07-21 下午5 14 40](https://user-images.githubusercontent.com/107826742/180190673-e64e50dd-7231-4aa7-9164-0c5e90078687.png)
we can see the auth_type is 'unspecified' rather than 'nosasl'.  

4. create foreign table which mapping with the existing table on hive:
'CREATE FOREIGN TABLE farticle
(
id  int,
title  TEXT,
body TEXT
)
SERVER hdfs_server
OPTIONS (dbname 'default', table_name 'pgmap');
'
I would get error like :
![截屏2022-07-21 下午6 10 03](https://user-images.githubusercontent.com/107826742/180189389-554ccf30-9ecd-4132-8b9b-0b1fc5aabdc9.png)

I have check the code in hive_client.cpp(605~614), it seems the hive client connection failed.
'
rc = g_jni->CallIntMethod(g_objJdbcClient, g_DBPrepare,
							con_index,
							g_jni->NewStringUTF(query),
							maxRows,
							g_objMsgBuf);
	if (rc < 0)
	{
		rv = (jstring)g_jni->CallObjectMethod(g_objMsgBuf, g_getVal);
		*errBuf = (char *)g_jni->GetStringUTFChars(rv, &isCopy);
	}

' 
The rc would be -1. 

The java version on my env is
openjdk version "11.0.15" 2022-04-19
OpenJDK Runtime Environment (build 11.0.15+10-Ubuntu-0ubuntu0.20.04.1)
OpenJDK 64-Bit Server VM (build 11.0.15+10-Ubuntu-0ubuntu0.20.04.1, mixed mode, sharing)

Could anyone help to figure out whether I am using it in a wrong way or there is anything wrong with my env? Thanks!

**Comment by sravanvelag** [comment]
Hi, can you please share the details of what the issue was and how it was resolved?
